### PR TITLE
Add ability to limit notification fetch

### PR DESCRIPTION
**Pull request by emulienfou**
Pull Request for issue #14

### CODE REVIEW

**Comment by LeandroLuccerini** [comment]
What about adding also an offset for pagination?

**Comment by emulienfou** [comment]
Offset added, suggested by @leandro980 
Thanks for the idea

**Comment by maximilienGilet** [comment]
Great idea !

Thanks

**Comment by LeandroLuccerini** [comment]
Speaking of pagination, i could work on adding a controller that uses [knp-paginator-bundle](https://github.com/KnpLabs/KnpPaginatorBundle). 

The steps that I will follow are:

1. Adding a dependency on knp-paginator-bundle to composer;
2. Adding a method to _NotifiableNotificationRepository.php_ that returns the query needed to the paginator;
3. Adding a controller (and a route) such as `listPaginatedNotificationAction`  that renders the specific template
4. Adding a template that renders the list paginated
5. Adding a new case to the `mgilet_notification_generate_path` in _NotificationExtension.php_ for the new route

Do you think it should be a good idea?

**Comment by flavienaudin** [comment]
Hi, 
I think this is a good idea. But I would like to warn you about a potential bug when using setFirstResult and setMaxResult with join query : http://www.christophe-meneses.fr/article/setmaxresults-limite-le-resultat-de-mes-jointures

Do you think it can occurred with your modification ? 

By the way, Thank you for your work

**Comment by LeandroLuccerini** [comment]
Hi @flavienaudin ,
knp-paginator uses [Doctrine Paginator ](https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber/UsesPaginator.php#L45) so i think it's not a problem in this case.

**Pull request merged**
