### PR TITLE
Override Entity notification

### PR DESCRIPTION
**Pull request by emulienfou**
Here is a PR to the issue #30.

## What did I do?
1. The entity class `Entity\Notification` has been removed
2. All code inside `Entity\Notification` has been moved to `Model\Notification`
3. This new class is a `MappingSuperClass`, this now able the user to create a custom `Notification` entity class in his own application

## BC break
Accepting this PR means, all users need to create on their own app an `Entity\Notification` class, such as:
```php
<?php

namespace Acme\Entity;

use Doctrine\ORM\Mapping as ORM;
use Mgilet\NotificationBundle\Model\Notification as NotificationModel;

/**
 * Class Notification
 * @ORM\Entity
 *
 * @package Acme\Entity
 */
class Notification extends NotificationModel
{
}
```

They also need to define entity resolution in Doctrine configuration, such as:
```yaml
doctrine:
  orm:
    resolve_target_entities:
      Mgilet\NotificationBundle\Entity\Notification: Acme\Entity\Notification
```

I think is a very interesting feature to add to the future version!

### CODE REVIEW

**Comment by maximilienGilet** [comment]
Hi @emulienfou, thanks for the contribution !

As you said, this is a big change for the bundle. The initial goal of the bundle is to be very easy and fast to install and use. 

This PR introduces more complexity to the user. Maybe we could work on making this a non breaking change. 
We could keep the `Notification` entity with the new MappingSuperClass and be able to set the `resolve_target_entities` to get custom `Notification`. It could look something like : 

```yaml
doctrine:
  orm:
    resolve_target_entities:
      Mgilet\NotificationBundle\Entity\Notification: Acme\Entity\Notification
```

I don't have time to do this work for the moment, but this could be featured in the next version of the bundle

**Comment by emulienfou** [comment]
Hi @maximilienGilet, I had the same idea to keep the `Notification` entity class, however when a user want to override this entity, it couldn't use the same table name.

Currently, I've got an error of duplicate table name by Doctrine, when doing exactly what you mention!

**Comment by emulienfou** [comment]
OK so I just add the new `Entity\Notification` class who extends the `Model\Extension` class.

So, by default the bundle will use the `Mgilet\NotificationBundle\Entity\Notification` class.
If someone wants to override this entity, like you said he just need to add:

```yaml
doctrine:
  orm:
    resolve_target_entities:
      Mgilet\NotificationBundle\Entity\Notification: Acme\Entity\Notification
```

**Comment by maximilienGilet** [comment]
Yay ! Thanks for the additional work !

I will test it later then merge and tag 3.1.0

cheers 👍

**Comment by emulienfou** [comment]
Adding new `NotificationInterface` if user want to override the `NotificationManager` class.
So, to override the `Notification` entity class, user need to implement this interface like:
```php
<?php

namespace Acme\Entity;

use Doctrine\ORM\Mapping as ORM;
use Mgilet\NotificationBundle\Entity\NotificationInterface;
use Mgilet\NotificationBundle\Model\Notification as NotificationModel;

/**
 * Class Notification
 * @ORM\Entity
 *
 * @package Acme\Entity
 */
class Notification extends NotificationModel implements NotificationInterface
{
}
```

**Comment by LeandroLuccerini** [comment]
I was looking for a "type" field in notification, just to add styling in twig rendering (success, danger, warning... bootstrap style). Great enhancement!

**Comment by flavienaudin** [comment]
Hi Maximilien,
I'm just installing your bundle that looks very promising and I was looking for the possibility to extend the Notification class. Do you know when the version 3.1, including this PR, will be released ? 
Also, the other PR #40 by @emulienfou to limit the number of fetched notifications looks interesting, do you think about including it in the version 3.1 too ?

Thank you for your work and if I implement some new feature, I'll be pleased to proposed enhancement too.

Flavien

**Comment by maximilienGilet** [comment]
Hi @flavienaudin I just merged this pull request. 

I think the new 3.1 version will be out today 🎉

**Comment by flavienaudin** [comment]
Thanks :+1:

**Comment by LeandroLuccerini** [comment]
I got a problem here, maybe you could help.
I've added this configuration

```
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Mgilet\NotificationBundle\Entity\Notification: App\Entity\Notification\Notification
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

Then i wrote my notification class

```
namespace App\Entity\Notification;


use Doctrine\ORM\Mapping as ORM;
use Mgilet\NotificationBundle\Model\Notification as NotificationModel;
use Mgilet\NotificationBundle\Entity\NotificationInterface;

/**
 * Class Notification
 *
 * @ORM\Entity
 * @package App\Entity\Notification
 */
class Notification extends NotificationModel implements NotificationInterface
{

    /**
     * @var string $id
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="string")
     */
    protected $id;

    /**
     * @var string $type
     *
     * @ORM\Column(type="string", name="type", nullable=true)
     */
    protected $type;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string|null $type
     * @return Notification
     */
    public function setType(string $type = null): self
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getType() : ?string
    {
        return $this->type;
    }

}
```

But when i try to store the notification t raises an error 

> Attempted to call an undefined method named "setType" of class "Mgilet\NotificationBundle\Entity\Notification".

This is the code i used

```
// $notification is a personal object that contains needed data such as subject type etc

$mgiletNotification = $this->notificationManager->createNotification($notification->subject,
$notification->message, $notification->link);
$mgiletNotification->setDate(new \DateTime($notification->stringDate));
// This is the error "setType"
$mgiletNotification->setType($notification->getType());
$this->notificationManager->addNotification($notifiables, $mgiletNotification, true);
$notification->id = $mgiletNotification->getId();
```
It seems like the notification manager doesn't resolve the orm mapping to my new Notification class... is it possible?

**Comment by murilozilli** [comment]
@leandro980 I had the same problem, apparently you need to override NotificationManager too if you want to override the entity.

**Comment by maximilienGilet** [comment]
Thanks @leandro980, version 4.0 is out with your PR. This should now be fixed 👍

**Pull request merged**
